// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "mattjam",
    "name": "MattJam",
    "description": "MattJam collaborative white board plugin for Mattermost.",
    "homepage_url": "https://github.com/AbderrahmaneMouzoune/mattermost-plugin-mattjam",
    "support_url": "https://github.com/AbderrahmaneMouzoune/mattermost-plugin-mattjam/issues",
    "release_notes_url": "https://github.com/AbderrahmaneMouzoune/mattermost-plugin-mattjam/releases/tag/v1.0.0",
    "icon_path": "assets/icon.svg",
    "version": "1.0.0",
    "min_server_version": "5.2.0",
    "server": {
        "executables": {
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": [
            {
                "key": "MattJamURL",
                "display_name": "MattJam Server URL:",
                "type": "text",
                "help_text": "The URL for your MattJam server, for example https://mattjam.example.com.",
                "placeholder": "https://www.figma.com/figjam/",
                "default": "https://www.figma.com/figjam/"
            },
            {
                "key": "MattJamNamingScheme",
                "display_name": "MattJam Meeting Names:",
                "type": "radio",
                "help_text": "Select how meeting names are generated by default. Users can override this setting with '/mattjam settings'.",
                "placeholder": "",
                "default": "words",
                "options": [
                    {
                        "display_name": "Random English words in title case (e.g. PlayfulDragonsObserveCuriously)",
                        "value": "words"
                    },
                    {
                        "display_name": "UUID (universally unique identifier)",
                        "value": "uuid"
                    },
                    {
                        "display_name": "Mattermost context specific names. Combination of team name, channel name, and random text in Public and Private channels; personal meeting name in Direct and Group Message channels.",
                        "value": "mattermost"
                    },
                    {
                        "display_name": "Allow user to select meeting name",
                        "value": "ask"
                    }
                ]
            },
            {
                "key": "MattJamJWT",
                "display_name": "Use JWT Authentication for MattJam:",
                "type": "bool",
                "help_text": "(Optional) If your MattJam server uses JSON Web Tokens (JWT) for authentication, set this value to true.",
                "placeholder": "",
                "default": null
            },
            {
                "key": "MattJamAppID",
                "display_name": "App ID for JWT Authentication:",
                "type": "text",
                "help_text": "(Optional) The app ID used for authentication by the MattJam server and JWT token generator.",
                "placeholder": "",
                "default": null
            },
            {
                "key": "MattJamAppSecret",
                "display_name": "App Secret for JWT Authentication:",
                "type": "text",
                "help_text": "(Optional) The app secret used for authentication by the MattJam server and JWT token generator.",
                "placeholder": "",
                "default": null
            },
            {
                "key": "MattJamLinkValidTime",
                "display_name": "Meeting Link Expiry Time (minutes):",
                "type": "number",
                "help_text": "(Optional) The number of minutes from when the meeting link is created to when it becomes invalid. Minimum is 1 minute. Only applies if using JWT authentication for your MattJam server.",
                "placeholder": "",
                "default": 30
            },
        ]
    }
}
`);

export default manifest;
export const id: string = manifest.id;
export const version: string = manifest.version;
